# Generated by Django 6.0.3 on 2026-03-21 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_address_address_line_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('whipping', 'Whipping Cream'), ('buttercream', 'Buttercream')], max_length=20)),
                ('weight', models.CharField(choices=[('500g', '500g'), ('1kg', '1kg'), ('2kg', '2kg')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product')),
            ],
        ),
    ]
