# Generated by Django 6.0.3 on 2026-03-21 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.address'),
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
