# Generated by Django 6.0.3 on 2026-03-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_order_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='whipping_price',
        ),
        migrations.AddField(
            model_name='product',
            name='buttercream_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
