# Generated by Django 6.0.3 on 2026-03-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_review_image_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cake_type',
            field=models.CharField(blank=True, choices=[('basic', 'Basic Cakes'), ('premium', 'Premium Cakes'), ('milk', 'Milk Cakes / Tres Leches')], max_length=20, null=True),
        ),
    ]
