# Generated by Django 6.0.3 on 2026-03-25 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_product_cake_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.address'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cake_type',
            field=models.CharField(blank=True, choices=[('basic', 'Basic Cake'), ('premium', 'Premium Cake'), ('milk', 'Milk Cake / Tres Leches')], max_length=20, null=True),
        ),
    ]
