# Generated by Django 6.0.3 on 2026-03-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_order_address_alter_product_cake_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=20),
        ),
    ]
