# Generated by Django 6.0.3 on 2026-04-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='whipping_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
