# Generated by Django 6.0.3 on 2026-08-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_product_whipping_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cookie_pack_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='cookie_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
