# Generated by Django 6.0.3 on 2026-09-03 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_product_cookie_pack_price_product_cookie_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cake', 'Cake'), ('cookie', 'Cookie'), ('brownie', 'Brownie'), ('cheesecake', 'Cheese Cake'), ('jarcake', 'Jar Cake'), ('cinnamonroll', 'Cinnamon Roll'), ('donut', 'Donut'), ('bomboloni', 'Bomboloni'), ('tiramisu', 'Tiramisu'), ('cupcakes', 'Cup Cakes'), ('muffins', 'Muffins'), ('tresleches', 'Tres Leches'), ('icecream', 'Ice Cream')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='shop.product')),
            ],
        ),
    ]
