# Generated by Django 6.0.3 on 2026-03-21 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_address_delete_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
